2018-10-19 13:28:34.509 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:28:34.510 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:33:07.632 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:33:07.632 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:33:40.503 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:33:40.503 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:35:25.614 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:35:25.615 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:36:25.347 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:36:25.347 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:36:55.018 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:36:55.018 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 13:37:56.485 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:37:56.485 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 13:39:16.025 [error] <0.107.0> gen_server <0.107.0> terminated with reason: no such process or port in call to gen_server:call(chat_room, {start_child,{"default",{"default",start_link,[]},permanent,5000,chat_room,["default"]}}, infinity) in gen_server:call/3 line 212
2018-10-19 13:39:16.027 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chat_room, {start_child,{"default",{"default",start_link,[]},permanent,5000,chat_room,["default"]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 13:39:16.027 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chat_room, {start_child,{"default",{"default",start_link,[]},permanent,5000,chat_room,["default"]}}, infinity) in context child_terminated
2018-10-19 13:39:16.027 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.027 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.027 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.027 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.027 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.028 [error] <0.214.0> CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.028 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-10-19 13:49:18.032 [error] <0.107.0> gen_server <0.107.0> terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{default,start_link,[default]},permanent,5000,chat_room,[default]}}, infinity) in gen_server:call/3 line 212
2018-10-19 13:49:18.052 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{default,start_link,[default]},permanent,5000,chat_room,[default]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 13:49:18.052 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{default,start_link,[default]},permanent,5000,chat_room,[default]}}, infinity) in context child_terminated
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.214.0> CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.216.0> CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-10-19 14:02:54.328 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: call to undefined function local:init([], {local,chat_manager}) in gen_server:init_it/6 line 352
2018-10-19 14:02:54.365 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason call to undefined function local:init([], {local,chat_manager}) in context start_error
2018-10-19 14:02:54.365 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{undef,[{local,init,[[],{local,chat_manager}],[]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 14:20:49.273 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours exited with reason: call to undefined function local:init([], {local,chatroom_sup}) in gen_server:init_it/6 line 352
2018-10-19 14:20:49.292 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason call to undefined function local:init([], {local,chatroom_sup}) in context start_error
2018-10-19 14:20:49.292 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{undef,[{local,init,[[],{local,chatroom_sup}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 14:21:41.183 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours exited with reason: call to undefined function local:init([], {local,chatroom_sup}) in gen_server:init_it/6 line 352
2018-10-19 14:21:41.187 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason call to undefined function local:init([], {local,chatroom_sup}) in context start_error
2018-10-19 14:21:41.187 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{undef,[{local,init,[[],{local,chatroom_sup}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 14:22:38.760 [error] <0.107.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:22:38.779 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:22:38.779 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:22:39.780 [error] <0.212.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:22:39.780 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:22:39.780 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:22:40.781 [error] <0.213.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:22:40.781 [error] <0.213.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:22:40.782 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.213.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:24:49.839 [error] <0.107.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:24:49.854 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:24:49.854 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:24:50.855 [error] <0.212.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:24:50.855 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:24:50.855 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:26:10.164 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 14:26:10.184 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 14:26:10.184 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 14:26:11.185 [error] <0.212.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 14:26:11.185 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 14:26:11.186 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 14:27:55.158 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 14:27:55.174 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 14:27:55.175 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:21.579 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:21.594 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:21.595 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:22.597 [error] <0.212.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:22.597 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:22.597 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:23.598 [error] <0.213.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:23.599 [error] <0.213.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:23.599 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.213.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:24.599 [error] <0.214.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:24.600 [error] <0.214.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:24.600 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.214.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:25.601 [error] <0.215.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:25.601 [error] <0.215.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:25.602 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.215.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:26.603 [error] <0.216.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:26.604 [error] <0.216.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:26.604 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.216.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:26.604 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.216.0> exit with reason reached_max_restart_intensity in context shutdown
2018-10-19 15:26:50.100 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40
2018-10-19 15:26:50.116 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 15:26:50.117 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 15:28:40.121 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40
2018-10-19 15:28:40.137 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 15:28:40.138 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 15:33:34.228 [error] <0.212.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40
2018-10-19 15:33:34.231 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 15:33:34.234 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 16:29:56.800 [error] <0.108.0> Supervisor {global,chatroom_sup} had child default started with chat_room:start_link(default) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:29:56.801 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,default,{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:29:56.801 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,default,{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:30:28.887 [error] <0.108.0> Supervisor {global,chatroom_sup} had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:30:28.887 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:30:28.887 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:32:19.066 [error] <0.108.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:32:19.066 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:32:19.066 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:33:26.453 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:33:26.453 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:33:26.454 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:34:12.420 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:34:12.421 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:34:12.421 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:38:12.167 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:38:12.167 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:38:12.167 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:42:04.706 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:42:04.707 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:42:04.707 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:42:51.051 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:42:51.052 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:42:51.052 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 17:24:33.004 [error] <0.109.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 40
2018-10-19 17:24:33.004 [error] <0.109.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 17:24:33.005 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.109.0> exit with reason no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 17:25:34.521 [error] <0.109.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[newone]}}} in chat_manager:handle_call/3 line 40
2018-10-19 17:25:34.521 [error] <0.109.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[newone]}}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 17:25:34.523 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.109.0> exit with reason no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[newone]}}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 17:29:52.040 [error] <0.109.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},temporary,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 41
2018-10-19 17:29:52.066 [error] <0.109.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},temporary,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 41 in gen_server:terminate/7 line 812
2018-10-19 17:29:52.066 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.109.0> exit with reason no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},temporary,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 41 in context child_terminated
2018-10-19 18:22:25.426 [error] emulator Error in process <0.214.0> with exit value:
{[{reason,undef},{mfa,{chat_handler,websocket_init,3}},{stacktrace,[{cowboy_req,parse_qs,[{http_req,#Port<0.3359>,ranch_tcp,keepalive,<0.214.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51814},<<"localhost">>,undefined,8080,<<"/ws">>,undefined,<<"room=myroom">>,undefined,[],[{<<"host">>,<<"localhost:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:62.0) Gecko/20100101 Firefox/62.0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>},{<<"accept-language">>,<<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"sec-websocket-version">>,<<"13">>},{<<"origin">>,<<"http://localhost:8080">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate">>},{<<"sec-websocket-key">>,<<"OIC+9aek6/WOnDIJWZK0dw==">>},{<<"dnt">>,<<"1">>},{<<"connection">>,<<"keep-alive, Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>}],[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"keep-alive">>,<<"upgrade">>]}],undefined,[{websocket_compress,false},{websocket_version,13}],waiting,undefined,<<>>,false,waiting,[],<<>>,undefined}],[]},{chat_handler,websocket_init,3,[{file,"src/chat_handler.erl"},{line,20}]},{cowboy_websocket,handler_init,3,[{file,"src/cowboy_websocket.erl"},{line,140}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]},{req,[{socket,#Port<0.3359>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.214.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},51814}},{host,<<"localhost">>},{host_info,undefined},{port,8080},{path,<<"/ws">>},{path_info,undefined},{qs,<<"room=myroom">>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:62.0) Gecko/20100101 Firefox/62.0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>},{<<"accept-language">>,<<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"sec-websocket-version">>,<<"13">>},{<<"origin">>,<<"http://localhost:8080">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate">>},{<<"sec-websocket-key">>,<<"OIC+9aek6/WOnDIJWZK0dw==">>},{<<"dnt">>,<<"1">>},{<<"connection">>,<<"keep-alive, Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"keep-alive">>,<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{opts,[]}],[{cowboy_websocket,handler_init,3,[{file,"src/cowboy_websocket.erl"},{line,157}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 18:22:25.427 [error] <0.214.0> Ranch listener http terminated in chat_handler:websocket_init/3 with reason: call to undefined function cowboy_req:parse_qs({http_req,#Port<0.3359>,ranch_tcp,keepalive,<0.214.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51814},<<"...">>,...})
2018-10-19 23:36:36.205 [error] emulator Error in process <0.214.0> with exit value:
{{try_clause,{ok,{state,<<"room1">>,<<"user)">>}}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:36:36.205 [error] <0.214.0> Ranch listener http terminated with reason: no try clause matching {ok,{state,<<"room1">>,<<"user)">>}} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:38:18.967 [error] emulator Error in process <0.213.0> with exit value:
{{try_clause,{ok,{state,<<"room1">>,<<"user73284">>}}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:38:18.967 [error] <0.213.0> Ranch listener http terminated with reason: no try clause matching {ok,{state,<<"room1">>,<<"user73284">>}} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:39:44.846 [error] emulator Error in process <0.216.0> with exit value:
{{try_clause,{ok,{state,<<"room1">>,<<"alex">>}}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:39:44.846 [error] <0.216.0> Ranch listener http terminated with reason: no try clause matching {ok,{state,<<"room1">>,<<"alex">>}} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:40:19.538 [error] emulator Error in process <0.213.0> with exit value:
{{try_clause,{ok,undefined_state}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:40:19.538 [error] <0.213.0> Ranch listener http terminated with reason: no try clause matching {ok,undefined_state} in cowboy_websocket:handler_call/7 line 598
